### ISSUE TITLE
Use of Defibox oracle for USD based price valuation

### ISSUE THREAD

**Issue by DenisCarriere** [pomelo-io/pomelo.app#3]
Perhaps denominating in $USD would most likely be the easier option for accepting multi-currency

Also, using averaged priced oracles which are pegged to $USD

Defibox Oracle supports a good amount of tokens on EOS already, which is very quite a challenge to manipulate in price due to the average price.

Supported tokens:
- EOS
- PBTC
- PETH
- BOX
- USN
- DEX
- DFS

https://bloks.io/account/oracle.defi?loadContract=true&tab=Tables&account=oracle.defi&scope=oracle.defi&limit=100&table=prices

**Comment by YaroShkvorets** [comment]
Done

`app.pomelo::token` now takes oracle id instead of pair_id as 4th argument: https://github.com/pomelo-io/pomelo.app/blob/main/app.pomelo.hpp#L658
